### ISSUE TITLE
Review request: automated Dutch translations for new permission dialogue

### ISSUE THREAD

**Issue by aral** [small-tech/comet#23]
@sexybiggetje If you get a moment, could you please review the automated Dutch translations I added for the new permissions dialogue that appears at the start and let me know if I should make any changes:

```po
#: src/WelcomeWindow.vala:143
msgid "Use Comet as your Git commit message editor?"
msgstr "Wil je Comet gebruiken als je Git commit-berichteditor?"

#: src/WelcomeWindow.vala:144
msgid "This will update your Git configuration for you."
msgstr "Hiermee wordt je Git-configuratie voor je bijgewerkt."

#: src/WelcomeWindow.vala:150
msgid "No"
msgstr "Nee"

#: src/WelcomeWindow.vala:153
msgid "Yes"
msgstr "Ja"
```

(I included the “Wil je” even though I cut it out of the English version as I wasn’t use whether it would read as “using” without it.)

You can see a screenshot of the dialogue here: https://github.com/elementary/appcenter-reviews/pull/225#issuecomment-989934480

**Comment by sexybiggetje** [comment]
Dutch is a language of exceptions, but the timing of the English sentence is in the future, and so is the message on line 143; I would rather make the timing of line 144 more clear on the timing, and thus replace the wordt je with zal worden like the following sentence: "Hiermee zal je Git-configuratie voor je worden bijgewerkt.". Both sentence structures are written in future time, but the current  translation better translates as "will happen", and my proposed one more like "this will make it happen" if that's a clear comparison.

Wil je is preferred, so that's a good move, it is clear without it, but it sounds a bit more rude. But I guess you can say that for English as well.

**Comment by aral** [comment]
@sexybiggetje Thanks again, Martijn, updated based on your review. Closing :)
